import type { Course } from "./data";

export const COURSES: Course[] = [
  {
    code: "CCA",
    title: "CCA",
    fullTitle: "Certificate in Computer Application",
    duration: "3 Months",
    durationMonths: 3,
    icon: "computer",
    level: "Beginner",
    popular: true,
    accent: "from-brand-400 to-brand-600",
    topics: [
      "Computer Fundamental",
      "Components & Devices of Computer",
      "Concept of DOS",
      "Concept & Properties of Windows",
      "Ms-Word: Formatting, Tables, Drawing, Mail Merge",
      "Ms-Excel: Formulas, Functions, Charts",
      "Ms-Powerpoint: Slides, Animation, Transition",
      "Internet, Web Browsing & Email",
      "Typing - Hindi & English",
    ],
  },
  {
    code: "CFA",
    title: "CFA",
    fullTitle: "Certificate in Financial Accounting",
    duration: "3 Months",
    durationMonths: 3,
    icon: "calculator",
    level: "Beginner",
    popular: true,
    accent: "from-rose-400 to-brand-600",
    topics: [
      "Fundamental of Accounts",
      "Accounting Concepts & Terms",
      "Types of Accounts",
      "Rules of Debit & Credit",
      "Journal Entry & Journalising",
      "Introduction to Tally Prime",
      "Company Creation & Accounts Management",
      "GST Reports & GST Returns",
      "Payroll, TDS, BRS & Back-Up",
    ],
  },
  {
    code: "CPT",
    title: "CPT",
    fullTitle: "Computer Professional Training",
    duration: "3 Months",
    durationMonths: 3,
    icon: "monitor",
    level: "Beginner",
    accent: "from-pink-400 to-brand-600",
    topics: [
      "Basic of Computer",
      "Operating System (DOS / Windows)",
      "Ms-Office Suite",
      "Internet & Database",
      "Typing Practice",
      "Web Browsing & E-Mail",
    ],
  },
  {
    code: "DCA",
    title: "DCA",
    fullTitle: "Diploma in Computer Application",
    duration: "6 Months",
    durationMonths: 6,
    icon: "layers",
    level: "Intermediate",
    popular: true,
    accent: "from-brand-500 to-purple-500",
    topics: [
      "Basic of Computer",
      "Operating System",
      "Ms-Word, Ms-Excel, Ms-Powerpoint",
      "Internet & E-Mail",
      "Database (Ms-Access)",
      "Introduction to Database, Tables, Sorting & Filtering",
      "Query, Forms & Reports",
    ],
  },
  {
    code: "DFA",
    title: "DFA",
    fullTitle: "Diploma in Financial Accounting",
    duration: "6 Months",
    durationMonths: 6,
    icon: "ledger",
    level: "Intermediate",
    accent: "from-rose-500 to-brand-600",
    topics: [
      "Basic of Computer & Operating System",
      "Ms-Office",
      "Internet & E-Mail",
      "Basic Manual Accounting",
      "Tally Prime (Financial Accounting)",
      "Company Creation, Stock & Godown",
      "Invoicing, Billing & Discount",
      "GST, TDS, Payroll & Financial Statements",
    ],
  },
  {
    code: "DTP",
    title: "DTP",
    fullTitle: "Diploma in Desktop Publishing",
    duration: "6 Months",
    durationMonths: 6,
    icon: "palette",
    level: "Intermediate",
    accent: "from-fuchsia-400 to-brand-600",
    topics: [
      "Basic of Computer & Ms-Office",
      "Adobe PageMaker: Introduction & Toolbox",
      "Placing Text & Image, Formatting Graphics",
      "CorelDraw: Drawing, Coloring & Effects",
      "Adobe Photoshop: Manipulation, Layers & Effects",
      "Practical Assignments",
    ],
  },
  {
    code: "ADCA",
    title: "ADCA",
    fullTitle: "Advance Diploma in Computer Application",
    duration: "12 Months",
    durationMonths: 12,
    icon: "award",
    level: "Advanced",
    popular: true,
    accent: "from-brand-600 to-purple-600",
    topics: [
      "Basics of Computer, Components & Devices",
      "Operating System - DOS, Windows, Properties",
      "Ms-Office - Word, Excel, Powerpoint",
      "Internet, ChatGPT, Gemini & AI",
      "Ms-Access Database, Query, Forms & Reports",
      "Tally Prime with GST & TDS",
      "DTP - PageMaker, CorelDraw, Photoshop",
      "HTML Web Designing",
      "Computer Typing - Hindi & English",
    ],
  },
  {
    code: "HNS",
    title: "Hardware & Networking",
    fullTitle: "Computer & Laptop Servicing",
    duration: "6 Months",
    durationMonths: 6,
    icon: "chip",
    level: "Intermediate",
    accent: "from-rose-400 to-purple-500",
    topics: [
      "Computer Assembling & Parts",
      "Installation of Operating System",
      "Troubleshooting & Hardware Repair",
      "Laptop Servicing & Upgrade",
      "Networking Basics & LAN Setup",
      "Printer, Scanner & Peripherals",
    ],
  },
  {
    code: "WD",
    title: "Web Designing",
    fullTitle: "Web Designing & Software Development",
    duration: "6 Months",
    durationMonths: 6,
    icon: "code",
    level: "Intermediate",
    accent: "from-purple-400 to-brand-500",
    topics: [
      "Introduction to HTML",
      "Designing a Webpage & Page Formatting",
      "Text Items & Objects",
      "Software Development Basics",
      "Data Analytics Fundamentals",
      "Python, C & Java",
    ],
  },
];